### ISSUE TITLE
Using Numpy differently can make this ~4x faster

### ISSUE THREAD

**Issue by migurski** [preyasu-rakshit/reaction-diffusion#1]
Hi, thanks for this excellent code! I’ve made some improvements to the way Numpy is applied that increase the iteration speed by ~400%. Would you welcome a pull request with these edits?

**Comment by preyasu-rakshit** [comment]
Hey, Thanks for checking out my project. I would love to see the changes you made.

I am still a beginner when it comes to git and github, and not quite sure what I need to do to 'welcome' a pull request. Is there something I have to enable or some settings I need to change? Let me know if that's the case, I will do it.

**Comment by migurski** [comment]
No, nothing special! I just wanted to know if I should spend the time putting one together.
